version: "3.6"
services:
  db:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

  goservice:
    container_name: goBackend
    build: "."
    ports:
      - "8080"
    depends_on:
      - db

  nginx:
    container_name: nginxWebserver
    build: 
      context: ./
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - "goservice"
volumes:
  db:
    driver: local