version: "3.6"
services:
  db:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
    storage_opt:
      size: '5G'
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

  goservice:
    container_name: api
    build: 
      context: ./
      dockerfile: ./webservice/.dockerfile
    ports:
      - "8080"
    env_file: ./webservice/.env
    depends_on:
      - db

  frontend:
    container_name: client
    build: 
      context: ./
      dockerfile: ./frontend.dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - goservice
    volumes:
      - /data/certs:/etc/nginx/certs
    
volumes:
  db:
    driver: local