version: "3.6"
services:
  db:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
    storage_opt:
      size: '5G'
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

  goservice:
    container_name: goBackend
    build: "."
    ports:
      - "8080"
    env_file: .env
    depends_on:
      - db

  frontend:
    container_name: mainsite
    build: 
      context: ./
      dockerfile: ./mainui/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - goservice
    volumes:
      - /data/certs:/etc/nginx/certs
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    
volumes:
  db:
    driver: local