name: Build and deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file webservice/.dockerfile --tag my-image-name:$(date +%s)

  build-frontend:
    needs: build-backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file frontend.dockerfile --tag my-image-name:$(date +%s)
        
  deploy:
    needs: build-frontend
    runs-on: ubuntu-latest
    steps:
    - name: ssh and run deploy script
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }}
        username: root
        password: ${{ secrets.SSH_PASS }}
        script: bash deploy.sh
