name: deploy callummclu.co.uk

on:
  workflow_run:
    workflows: [Frontend Build Check (Main Site & Links Site & Admin Site),WebService Build Check (golang backend)]
    types:
      - completed

jobs:
  - name: ssh and run deploy script
    uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }}
        username: root
        password: ${{ secrets.SSH_PASS }}
        script: bash deploy.sh
  