name: deploy callummclu.co.uk

on:
  workflow_run:
    workflows: [Frontend Build Check (Main Site & Links Site & Admin Site),WebService Build Check (golang backend)]
    types:
      - completed

jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest
    steps:
      - name: connect and pull
        run: ssh root@${{ secrets.SSH_HOST }} ${{ secrets.SSH_PASS }} "bash deploy.sh && exit"
