name: Frontend Build Check (Main Site & Links Site & Admin Site)

on:
  workflow_run:
    workflows: [WebService Build Check (golang backend)]
    types:
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file frontend.dockerfile --tag my-image-name:$(date +%s)
